version: '3.8'

services:
  postgres:
    container_name: postgres-1
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gamlgen:
    build:
      context: .
    environment:
      DB_HOST: ${DB_HOST_CLIENT}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - 0.0.0.0:8000:8000

  gama-server:
    container_name: gama-server
    image: gamaplatform/gama:1.9.2
    command: '-socket 7000'
    #ports:
    #  - 0.0.0.0:7000:7000
    depends_on:
      - postgres
      - gamlgen

volumes:
  postgres-data:
